name: "Setup Java and Maven"
description: "Setup Java and Maven"
inputs:
  cache-version:
    description: "The version of the cache to use"
    required: true
  java-version:
    description: "The version of Java to use"
    required: false
    default: |
      8
      17
  java-distribution:
    description: "The distribution of Java to use"
    required: false
    default: temurin
runs:
  using: "composite"
  steps:
    - name: "Setup Java"
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
    - name: "Cache Maven packages"
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository/*/*
          !~/.m2/repository/fr/sii
        key: ${{ runner.os }}-m2-${{ inputs.cache-version }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-${{ inputs.cache-version }}-
    - name: "Upload Maven cache for debugging"
      if: runner.debug && hashFiles('~/.m2/repository')
      uses: ./.github/actions/archive-and-upload
      with:
        working-directory: ~/.m2/repository
        file-pattern: "**"
        artifact-name: maven-repository-cache--${{ github.job }}--${{ matrix.os }}
