spring:
  config:
    import:
      - spring-boot-1.5.x.yml
      - spring-boot-2.1.x.yml
      - spring-boot-2.2.x-2.7.x--properties+dependency-management.yml
      - spring-boot-3.0.x.yml
      - standalone.yml

spring.initializer.url: http://localhost:8050/starter.zip

server:
  port: 7894
