server:
  port: 8050
initializr:
  bootVersions:
    - id: 1.5.22.RELEASE
      name: 1.5.22
      default: false
    - id: 2.1.18.RELEASE
      name: 2.1.18
      default: true
    - id: 2.2.13.RELEASE
      name: 2.2.13
      default: false
    - id: 2.3.12.RELEASE
      name: 2.3.12
      default: false
    - id: 2.4.13
      name: 2.4.13
      default: false
    - id: 2.5.15
      name: 2.5.15
      default: false
    - id: 2.6.15
      name: 2.6.15
      default: false
    - id: 2.7.12
      name: 2.7.12
      default: false
    - id: 3.0.7
      name: 3.0.7
      default: false
    - id: 3.1.0
      name: 3.1.0
      default: false
  javaVersions:
    - id: 17
      default: false
    - id: 15
      default: false
    - id: 14
      default: false
    - id: 13
      default: false
    - id: 12
      default: false
    - id: 11
      default: false
    - id: 1.8
      default: true
  languages:
    - name: Java
      id: java
      default: true
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      tags:
        build: gradle
        format: project
      default: false
      action: /starter.zip
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
      default: false
  dependencies:
    - name: Core
      content:
        - name: Configuration Processor
          id: configuration-processor
          groupId: org.springframework.boot
          artifactId: spring-boot-configuration-processor
          scope: compileOnly
          description: Generate metadata for your custom configuration keys
          starter: false
        - name: DevTools
          id: devtools
          groupId: org.springframework.boot
          artifactId: spring-boot-devtools
          scope: runtime
          description: Spring Boot Development Tools
          starter: false
        - name: Lombok
          id: lombok
          groupId: org.projectlombok
          artifactId: lombok
          scope: compileOnly
          description: Java annotation library which helps to reduce boilerplate code and code faster
          starter: false
    - name: Web
      content:
        - name: Web
          id: web
          description: Full-stack web development with Tomcat and Spring MVC
          facets:
            - web
    - name: Template Engines
      content:
        - name: Thymeleaf
          id: thymeleaf
          description: Thymeleaf templating engine, including integration with Spring
          facets:
            - web
        - name: Freemarker
          id: freemarker
          description: FreeMarker templating engine
          facets:
            - web
    - name: I/O
      content:
        - name: Mail
          id: mail
          description: javax.mail
