version: 2.1
orbs:
  slack: circleci/slack@3.2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      #---------------------------------------
      # restore cache from previous build
      #---------------------------------------
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - restore_cache:
          keys:
            - pit-history-{{ .Branch }}
      - run: cp -f ~/.pitest/* /tmp/ || echo 'no pitest history copied to /tmp'
      - run: ls -l /tmp/
      - run: ls -l ~/.pitest/ || echo ".pitest folder doesn't exist"
      #---------------------------------------
      # build test and generate reports
      #---------------------------------------
      - run: ci/./generate-documentation.sh
      - persist_to_workspace:
          root: .
          paths:
            - target
      #---------------------------------------
      # save/update cache
      #---------------------------------------
      - run: rm -rf ~/.m2/repository/fr/sii
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mkdir ~/.pitest || echo 'skip creating .pitest'
      - run: cp -f /tmp/*_pitest_history.bin ~/.pitest/ || echo 'no pitest history saved'
      - save_cache:
          paths:
            - ~/.pitest
          key: pit-history-{{ .Branch }}
      - run: ls -l /tmp/
      - run: ls -l ~/.pitest/ || echo ".pitest folder doesn't exist"
      #---------------------------------------
      # store build information
      #---------------------------------------
      - store_test_results:
          path: .
  deploy:
    docker:
      - image: alpine/git
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "9a:b0:42:93:73:3e:35:21:62:23:48:eb:79:88:17:d5"
      #---------------------------------------
      # deploy to Github Pages
      #---------------------------------------
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: git clone git@github.com:aurelien-baudet/ogham-dev-reports.git /tmp/ogham-dev-reports
      - run: mkdir -p /tmp/ogham-dev-reports/$CIRCLE_BRANCH && cp -r target/site/* /tmp/ogham-dev-reports/$CIRCLE_BRANCH
      - run: cd /tmp/ogham-dev-reports && git config user.email $GH_EMAIL && git config user.name $GH_NAME && git add . && git commit -m "add/update $CIRCLE_BRANCH" && git push
  notify:
    docker:
      - image: circleci/node:7.10
    steps:
      - slack/status:
          success_message: "*[success]* ${CIRCLE_JOB} Documentation and reports:
          
          * <https://aurelien-baudet.github.io/ogham-dev-reports/${CIRCLE_BRANCH}/index.html|Generated site>
          
          * <https://aurelien-baudet.github.io/ogham-dev-reports/${CIRCLE_BRANCH}/jacoco-aggregate/index.html|JaCoCo>
          
          * <https://codecov.io/gh/groupe-sii/ogham/branch/${CIRCLE_BRANCH}|Codecov>
          
          * <https://aurelien-baudet.github.io/ogham-dev-reports/${CIRCLE_BRANCH}/pit-reports/index.html|Mutation testing>"
workflows:
  generate-documentation:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - notify:
          requires:
            - deploy
