name: Documentation

on:
  push:
    branches-ignore:
      - 'gh-*'

jobs:
  mutation-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        module:
          - ogham-test-utils
          - ogham-core
          - ogham-template-thymeleaf-common
          - ogham-template-thymeleaf-v2
          - ogham-template-thymeleaf-v3
          - ogham-template-freemarker
          - ogham-email-javamail-jakarta
          - ogham-email-javamail-javax
          - ogham-email-sendgrid-v2
          - ogham-email-sendgrid-v4
          - ogham-sms-cloudhopper
          - ogham-sms-ovh
          - ogham-sms-smsglobal
#          - ogham-all
          - ogham-spring-boot-v1-autoconfigure
          - ogham-spring-boot-v2-autoconfigure
          - ogham-spring-boot-v3-autoconfigure
    name: "Mutation testing [${{ matrix.module }}]"
    steps:
      - uses: actions/checkout@v3
      - name: "Setup Java and Maven"
        uses: ./.github/actions/setup-java-and-maven
        with:
          cache-version: ${{ vars.CACHE_VERSION }}
      - name: "Run mutation tests"
        uses: ./.github/actions/mutation-tests
        with:
          module: ${{ matrix.module }}
          cache-version: ${{ vars.PITEST_CACHE_VERSION }}
        
  generate-documentation:
    needs: [mutation-tests]
    runs-on: ubuntu-latest
    name: "Generate documentation and site"
    steps:
      - uses: actions/checkout@v3
      - name: "Setup Java and Maven"
        uses: ./.github/actions/setup-java-and-maven
        with:
          cache-version: ${{ vars.CACHE_VERSION }}
      - name: "Generate documentation"
        uses: ./.github/actions/generate-documentation

  deploy:
    needs: [generate-documentation]
    environment: dev
    runs-on: ubuntu-latest
    name: "Deploy documentation"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Restore generated documentation"
        uses: ./.github/actions/download-and-extract
        with:
          artifact-name: documentation-with-showcase
          to-directory: target
      - name: "Clone ogham-dev-reports"
        uses: actions/checkout@v3
        with:
          repository: aurelien-baudet/ogham-dev-reports
          path: ogham-dev-reports
          token: ${{ secrets.DEV_REPORTS_GITHUB_TOKEN }}
      - name: "Add branch site to reports"
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          ci/./deploy-dev-reports.sh $BRANCH ${{ github.workspace }}/ogham-dev-reports
        
  slack-success:
    if: success()
    needs: [deploy]
    runs-on: ubuntu-latest
    name: "Slack"
    steps:
      - run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - uses: 8398a7/action-slack@v3
        with:
          text: |
            :white_check_mark: :blue_book: _${{ env.BRANCH }}_
            
            > Generated docs and reports:
            > • <https://aurelien-baudet.github.io/ogham-dev-reports/${{ env.BRANCH }}/index.html|Generated site>
            > • <https://aurelien-baudet.github.io/ogham-dev-reports/${{ env.BRANCH }}/jacoco-aggregate/index.html|JaCoCo>
            > • <https://codecov.io/gh/groupe-sii/ogham/branch/${{ env.BRANCH }}|Codecov>
            > • <https://aurelien-baudet.github.io/ogham-dev-reports/${{ env.BRANCH }}/pit-reports/index.html|Mutation testing>
            
          status: success
          fields: workflow,ref,message
          icon_url: https://github.com/groupe-sii/ogham/raw/master/src/site/resources/img/ogham-blue-256x256.png
          username: 'documentation'
          author_name: ''
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  slack-failure:
    if: failure()
    needs: [deploy]
    runs-on: ubuntu-latest
    name: "Slack"
    steps:
      - run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - uses: 8398a7/action-slack@v3
        with:
          text: |
            :x: :blue_book: _${{ env.BRANCH }}_
          status: failure
          fields: workflow,ref,message
          icon_url: https://github.com/groupe-sii/ogham/raw/master/src/site/resources/img/ogham-blue-256x256.png
          username: 'documentation'
          author_name: ''
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

