name: Update site

on:
  workflow_dispatch:
    inputs:
      current-version:
        description: 'The ogham version to display'
        required: true
        default: '3.0.0-SNAPSHOT'
      git-branch:
        description: 'The branch for the ogham version'
        required: true
        default: 'master'
        
jobs:
  mutation-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        module:
          - ogham-test-utils
          - ogham-core
          - ogham-template-thymeleaf-common
          - ogham-template-thymeleaf-v2
          - ogham-template-thymeleaf-v3
          - ogham-template-freemarker
          - ogham-email-javamail
          - ogham-email-sendgrid-v2
          - ogham-email-sendgrid-v4
          - ogham-sms-cloudhopper
          - ogham-sms-ovh
          - ogham-sms-smsglobal
          - ogham-all
          - ogham-spring-boot-v1-autoconfigure
          - ogham-spring-boot-v2-autoconfigure
    name: "Mutation testing [${{ matrix.module }}]"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java and Maven
        uses: ./.github/actions/setup-java-and-maven
        with:
          cache-version: ${{ secrets.CACHE_VERSION }}
          include-ogham: true
      - name: Run mutation tests
        uses: ./.github/actions/mutation-tests
        with:
          module: ${{ matrix.module }}
          cache-version: ${{ secrets.PITEST_CACHE_VERSION }}
          include-ogham: true

  generate-documentation:
    needs: [mutation-tests]
    runs-on: ubuntu-latest
    name: "Generate documentation and site"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java and Maven
        uses: ./.github/actions/setup-java-and-maven
        with:
          cache-version: ${{ secrets.CACHE_VERSION }}
      - name: "Generate documentation"
        uses: ./.github/actions/generate-documentation
        with:
          ogham-version: ${{ github.event.inputs.current-version }}
          git-branch: ${{ github.event.inputs.git-branch }}

  update-site:
    needs: [generate-documentation]
    environment: dev
    runs-on: ubuntu-latest
    name: "Update site"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java and Maven
        uses: ./.github/actions/setup-java-and-maven
        with:
          cache-version: ${{ secrets.CACHE_VERSION }}
          include-ogham: true
      - name: "Restore generated documentation - download"
        uses: actions/download-artifact@v3
        with:
          name: maven-build
          path: /tmp
      - name: "Restore generated documentation - extract"
        run: |
          tar -xzf /tmp/maven-build.tar.gz
      - name: "Clone gh-pages"
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
      - name: "Generate site in gh-pages"
        run:
          ./mvnw site:stage
              '-Pmutation-testing'
              '-Dsite.staging.dir=gh-pages'
              '-Ddoc.ogham.version=${{ github.event.inputs.current-version }}'
              '-Dgit.branch=${{ github.event.inputs.git-branch }}'
      - uses: actions/setup-python@v2
        with:
          python-version: 3.5
      - name: "Update list of versions"
        run: |
          python .tools/site/generate-site-index-and-versions.py 'gh-pages'
      - name: "Push site on gh-pages"
        working-directory: gh-pages
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
          git add .
          git commit -m "doc(site) Add/update documentation for ${{ github.event.inputs.current-version }} from ${{ github.event.inputs.git-branch }}"
          git push
                  
  slack-success:
    if: success()
    needs: [update-site]
    runs-on: ubuntu-latest
    name: "Slack"
    steps:
      - run: echo "BRANCH=${GITHUB_REF#refs/heads}" >> $GITHUB_ENV
      - uses: 8398a7/action-slack@v3
        with:
          text: |
            :white_check_mark: :books: ${{ github.event.inputs.release-version }}
          status: success
          fields: workflow,ref,message
          icon_url: https://github.com/groupe-sii/ogham/raw/master/src/site/resources/img/ogham-blue-256x256.png
          username: 'site'
          author_name: ''
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  slack-failure:
    if: failure()
    needs: [update-site]
    runs-on: ubuntu-latest
    name: "Slack"
    steps:
      - run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - uses: 8398a7/action-slack@v3
        with:
          text: |
            :x: :books: ${{ github.event.inputs.release-version }}
          status: failure
          fields: workflow,ref,message
          icon_url: https://github.com/groupe-sii/ogham/raw/master/src/site/resources/img/ogham-blue-256x256.png
          username: 'site'
          author_name: ''
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

